language: python
python: 2.7
os: linux
dist:
    - xenial

addons:
    apt:
        update: true

# testing with jdk8, on xenial
before_install:
    - sudo apt install -y repo git make gcc-arm-none-eabi binutils-arm-none-eabi python-pip python3-pip python-pyscard python-crypto openjdk-8-jdk maven ant curl

# installing dependencies
install:
    - sudo pip install intelhex
    - sudo pip3 install kconfiglib
    - curl -o /tmp/gnat-community-2018-20180524-arm-elf-linux64-bin http://mirrors.cdn.adacore.com/art/5b0c1227a3f5d7097625478d
    - chmod +x /tmp/gnat-community-2018-20180524-arm-elf-linux64-bin
    - git clone https://github.com/AdaCore/gnat_community_install_script.git /tmp/gnat_install
    - /tmp/gnat_install/install_package.sh /tmp/gnat-community-2018-20180524-arm-elf-linux64-bin /opt/adacore-arm-eabi

# setting build dir and correct path for installed tools
before_script:
    - python --version
    - mkdir build && cd build
    - export PATH=/opt/adacore-arm-eabi/bin:/usr/local/bin:$PATH

# let's sync and build
script:
    - git config --global color.ui true
    - repo init -u https://github.com/wookey-project/manifest.git -m disco407.xml && repo sync
    - echo 'CROSS_COMPILE=arm-eabi-' > setenv.local.sh
    - source setenv.sh
    - make boards/32f407disco/configs/disco_blinky_ada_defconfig
    - make


branches:
    only:
        - master
