language: python
python: 2.7
os: linux
dist:
    - xenial

addons:
    apt:
        update: true

before_install:
    - sudo apt install -y repo git make gcc-arm-none-eabi binutils-arm-none-eabi python-pip python3-pip python-pyscard python-crypto openjdk-11-jdk maven ant

install:
    - pip install intelhex
    - sudo pip3 install kconfiglib

script:
    - repo init -u https://github.com/wookey-project/manifest.git -m disco407.xml
    - repo sync

branches:
    only:
        - master
